-- Isolated database fixture only. Never run this setup against the application DB.
CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA auth; CREATE SCHEMA storage;
GRANT USAGE ON SCHEMA public,auth,storage TO anon,authenticated,service_role;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
CREATE FUNCTION storage.foldername(text) RETURNS text[] LANGUAGE sql IMMUTABLE AS $$SELECT string_to_array($1,'/')$$;
CREATE TABLE auth.users(id uuid PRIMARY KEY);
CREATE TABLE public.profiles(id uuid PRIMARY KEY,email text);
CREATE TABLE public.account_activation(user_id uuid PRIMARY KEY,active boolean,must_change_password boolean);
CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text,name text);
CREATE TABLE public.videos(id uuid PRIMARY KEY,owner_id uuid,file_name text,visibility text,storage_path text,preview_path text,preview_url text,processing_status text);
CREATE TABLE public.photos(id uuid PRIMARY KEY,owner_id uuid,file_name text,visibility text,storage_path text);
GRANT ALL ON storage.objects,public.videos,public.photos TO anon,authenticated,service_role;
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
CREATE POLICY old_permissive ON storage.objects USING(true) WITH CHECK(true);
INSERT INTO auth.users VALUES('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');
INSERT INTO public.profiles SELECT id,'fixture@example.test' FROM auth.users;
INSERT INTO videos VALUES('33333333-3333-4333-8333-333333333333','11111111-1111-4111-8111-111111111111','video','private','original.mp4',NULL,NULL,'ready');
INSERT INTO photos VALUES('44444444-4444-4444-8444-444444444444','11111111-1111-4111-8111-111111111111','photo','private','original.jpg');
